"""Grid Store: persists aligned spatiotemporal grids as compressed .npz files
with a JSON sidecar describing where the data came from."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .config import DX_KM, GRID, HIST_TIMES_H, LEADS_H


def save(path: str | Path, arrays: dict, meta: dict) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(path, **arrays)
    meta = {"grid": GRID, "dx_km": DX_KM, "hist_times_h": list(HIST_TIMES_H),
            "leads_h": list(LEADS_H), **meta}
    path.with_suffix(".json").write_text(json.dumps(meta, indent=2))


def load(path: str | Path) -> tuple[dict, dict]:
    path = Path(path)
    with np.load(path) as z:
        arrays = {k: z[k] for k in z.files}
    meta = json.loads(path.with_suffix(".json").read_text())
    return arrays, meta


def get_split(name: str, n: int, seed: int, data_dir: str | Path = "data") -> dict:
    """Load a synthetic split, generating and caching it on first use."""
    path = Path(data_dir) / f"synthetic_{name}_n{n}_seed{seed}.npz"
    if path.exists():
        return load(path)[0]
    from .synthetic import make_dataset
    arrays = make_dataset(n, seed)
    save(path, arrays, {"source": "synthetic", "split": name, "n": n, "seed": seed,
                        "note": "Generated by drishti_nowcast.synthetic. Not observational data."})
    return arrays
